server:
  port: 8088
spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:5680/inventory
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
